name: pocketa
description: ""
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.21.2
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  go_router: ^16.2.4
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.10.0
  collection: ^1.19.1
  easy_localization: ^3.0.8
  flutter_svg: ^2.2.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flutter_dotenv: ^6.0.0
  loading_animation_widget: ^1.3.0
  logger: ^2.6.1
  toastification: ^3.0.3
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  flutter_boring_avatars: ^2.0.1
  shimmer: ^3.0.0
  supabase_flutter: ^2.10.3
  
dev_dependencies:
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  riverpod_generator: ^3.0.3
  json_serializable: ^6.11.1
  build_runner: ^2.5.4
  freezed: ^3.2.3
  freezed_lint: ^0.0.12
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  
flutter:
  uses-material-design: true
  assets:
    - assets/langs/
    - assets/icon/logo.svg
    - .env

flutter_launcher_icons:
  image_path: assets/icon/icon.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#f9f9f9"
  image: assets/icon/icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    image: assets/icon/icon.png
    color: "#f9f9f9"
    icon_background_color: "#f9f9f9"